PolskaPaliwo/Models/CarAd.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System.ComponentModel.DataAnnotations;

namespace PolskaPaliwo.Models
{
    public class CarAd
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [Display(Name = "Content type")]
        [Required(ErrorMessage = "Uploading an image is required")]
        public string? ContentType { get; set; }
        public byte[]? Data { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required")]
        public string Price { get; set; }

        [Display(Name = "Currency")]
        [Required(ErrorMessage = "Currency is required")]
        public string Currency { get; set; }

        [Display(Name = "Condition")]
        [Required(ErrorMessage = "Condition is required")]
        public string Condition { get; set; }

        [Display(Name = "Brand")]
        [Required(ErrorMessage = "Brand is required")]
        public string Brand { get; set; }

        [Display(Name = "Model")]
        [Required(ErrorMessage = "Model is required")]
        public string Model { get; set; }

        [Display(Name = "Production year")]
        [Required(ErrorMessage = "Production year is required")]
        public string ProductionYear { get; set; }

        [Display(Name = "Mileage")]
        [Required(ErrorMessage = "Mileage is required")]
        public string Mileage { get; set; }

        [Display(Name = "Power")]
        [Required(ErrorMessage = "Power is required")]
        public string Power { get; set; }

        [Display(Name = "Engine displacement")]
        [Required(ErrorMessage = "Engine displacement is required")]
        public string EngineSize { get; set; }

        [Display(Name = "Fuel type")]
        [Required(ErrorMessage = "Fuel type is required")]
        public string FuelType { get; set; }

        [Display(Name = "Drive")]
        [Required(ErrorMessage = "Drive is required")]
        public string Drive { get; set; }

        [Display(Name = "Transmission")]
        [Required(ErrorMessage = "Transmission is required")]
        public string Transmission { get; set; }

        [Display(Name = "Type")]
        [Required(ErrorMessage = "Type is required")]
        public string Type { get; set; }

        [Display(Name = "Number of doors")]
        [Required(ErrorMessage = "Number of doors is required")]
        public string DoorsNumber { get; set; }

        [Display(Name = "Colour")]
        [Required(ErrorMessage = "Colour is required")]
        public string Colour { get; set; }

        [Display(Name = "Origin country")]
        [Required(ErrorMessage = "Origin country is required")]
        public string OriginCountry { get; set; }

        [Display(Name = "First owner")]
        [Required(ErrorMessage = "First owner is required")]
        public string FirstOwner { get; set; }

        [Display(Name = "Registration year")]
        [Required(ErrorMessage = "Registration year is required")]
        public string RegistrationYear { get; set; }

        [Display(Name = "Location")]
        [Required(ErrorMessage = "Location is required")]
        public string Location { get; set; }

        [Display(Name = "Telephone")]
        [Required(ErrorMessage = "Telephone is required")]
        public string Telephone { get; set; }

        [Display(Name = "Features")]
        public string[]? Features { get; set; }
        public string CreatorId { get; set; }

        public override bool Equals(object obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }

            CarAd other = (CarAd)obj;
            return Id == other.Id; // Compare based on Id
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }

    }
}

PolskaPaliwo/Controllers/CarAdController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using MimeKit;
using MongoDB.Driver;
using Newtonsoft.Json;
using PolskaPaliwo.Models;
using PolskaPaliwo.Repository;
using System.Runtime.Serialization.Formatters.Binary;

namespace PolskaPaliwo.Controllers
{
    public class CarAdController : Controller
    {
        private readonly ICarAdRepository _carAdRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public CarAdController(ICarAdRepository ICarAdRepository, UserManager<ApplicationUser> userManager)
        {
            _carAdRepository = ICarAdRepository;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //var carAds = _carAdRepository.GetAllCarAds();
            //return Ok(carAds); // Return cars as JSON for testing
            return Ok();
        }



        [Authorize]
        [HttpGet]
        public IActionResult UpdateToGenerateForm(string id)
        {
            CarAd carAdToUpdate = _carAdRepository.GetCarAdById(id);
            return View("UpdateFormView", carAdToUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CarAd carAd)
        {
            var userId = _userManager.GetUserId(this.User);
            string json = HttpContext.Session.GetString("SearchResults");
            if (json != null)
            {
                List<CarAd> searchResults = JsonConvert.DeserializeObject<List<CarAd>>(json);

                int index = searchResults.FindIndex(c => c.Id == carAd.Id);
                if (index != -1)
                {
                    searchResults[index] = carAd;
                }
                _carAdRepository.UpdateCarAd(carAd);

                ViewBag.SearchResults = searchResults; //first viewbag
                HttpContext.Session.SetString("SearchResults", JsonConvert.SerializeObject(searchResults));
                
                if (userId != null)
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    List<CarAd> recommendedAds = _carAdRepository.ListRecommendedCars(userId, user.PreviousIds);
                    ViewBag.RecommendedAds = recommendedAds; //second viewbag
                    return RedirectToAction("ResultsForPrevious");
                }

                return RedirectToAction("ResultsForPrevious");
            }

            if (userId != null)
            {
                _carAdRepository.UpdateCarAd(carAd);
            }

            return RedirectToAction("Index", "Home");
        }



        [Authorize]
        [HttpGet]
        public IActionResult DeleteToGenerateForm(string id)
        {
            var carAd = _carAdRepository.GetCarAdById(id);
            return View("DeleteComfirmationView", carAd);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var userId = _userManager.GetUserId(this.User);
            string json = HttpContext.Session.GetString("SearchResults");
            if (json != null)
            {
                List<CarAd> searchResults = JsonConvert.DeserializeObject<List<CarAd>>(json);
                searchResults.Remove(searchResults.Where(x => x.Id == id).First());
                _carAdRepository.DeleteCarAd(id);

                ViewBag.SearchResults = searchResults; //first viewbag
                HttpContext.Session.SetString("SearchResults", JsonConvert.SerializeObject(searchResults));

                
                if (userId != null)
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    var ids = user.PreviousIds.Split(',').ToList();
                    ids.RemoveAll(item => item == id); // Remove the item from the list using RemoveAll

                    string previousIds = string.Join(",", ids); // Reconstruct the string

                    List<CarAd> recommendedAds = _carAdRepository.ListRecommendedCars(userId, previousIds);
                    ViewBag.RecommendedAds = recommendedAds; //second viewbag
                    return RedirectToAction("ResultsForPrevious");
                }
                return RedirectToAction("ResultsForPrevious");
            }
            if (userId != null)
            {
                _carAdRepository.DeleteCarAd(id);
            }
            return RedirectToAction("Index", "Home");
        }




        [Authorize]
        [HttpGet]
        public IActionResult CreateToGenerateForm()
        {
            return View("CreateFormView");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(CarAd carAd, IFormFile pictureData)
        {
            if (pictureData != null && pictureData.Length > 0)
            {
                using (var stream = pictureData.OpenReadStream())
                {
                    byte[] buffer = new byte[pictureData.Length];
                    stream.Read(buffer, 0, (int)pictureData.Length);

                    carAd.Data = buffer;
                    string detectedContentType = MimeTypes.GetMimeType(pictureData.FileName);
                    carAd.ContentType = detectedContentType ?? pictureData.ContentType;
                }
            }
                

            carAd.CreatorId = _userManager.GetUserId(this.User);
            _carAdRepository.CreateCarAd(carAd);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult GetImage(string id) 
        {
            var carAd = _carAdRepository.GetCarAdById(id);
            if (carAd.ContentType.Length > 3)
            {
                return new FileContentResult(carAd.Data, carAd.ContentType);
            }
            return BadRequest();   
        }




        [HttpGet]
        public async Task<IActionResult> Details(string id, string source)
        {
            var carAd = _carAdRepository.GetCarAdById(id);
            ViewBag.Source = source;

            var userId = _userManager.GetUserId(this.User);
            if (userId != null)
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    if (user.PreviousIds == null)
                    {
                        user.PreviousIds += id.ToString();
                    }
                    else if (user.PreviousIds.Count(x => x == ',') == 4)
                    {
                        int idx = user.PreviousIds.IndexOf(',');
                        user.PreviousIds = user.PreviousIds.Substring(idx + 1);
                        user.PreviousIds += "," + id.ToString();
                    }
                    else
                    {
                        user.PreviousIds += "," + id.ToString();
                    }
                    await _userManager.UpdateAsync(user);
                }
            }
            return View("DetailedCarAdvertisementView", carAd);
        }


        [HttpPost]
        public async Task<IActionResult> SearchForCarAds(CarAd carAd)
        {
            var searchResults = _carAdRepository.SearchForCarAds(carAd).ToList();
            if (searchResults.Count != 0) //better 0 test needed
            {
                string json = JsonConvert.SerializeObject(searchResults);
                ViewBag.SearchResults = searchResults; //first viewbag
                HttpContext.Session.SetString("SearchResults", json);

                //await Console.Out.WriteLineAsync(json);


                var userId = _userManager.GetUserId(this.User);
                if (userId != null)
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user.PreviousIds != null && user.PreviousIds.Count(x => x == ',') == 4)
                    {
                        List<CarAd> recommendedAds = _carAdRepository.ListRecommendedCars(userId, user.PreviousIds);
                        ViewBag.RecommendedAds = recommendedAds; //second viewbag
                        return View("SearchResultsView");
                    }
                }

                return View("SearchResultsView");
            }
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public async Task<IActionResult> ResultsForPrevious()
        {
            string json = HttpContext.Session.GetString("SearchResults");
            if (json != null)
            {
                List<CarAd> searchResults = JsonConvert.DeserializeObject<List<CarAd>>(json);
                ViewBag.SearchResults = searchResults;
                var userId = _userManager.GetUserId(this.User);
                if (userId != null)
                {
                    var user = await _userManager.FindByIdAsync(userId);

                    List<CarAd> recommendedAds = _carAdRepository.ListRecommendedCars(userId, user.PreviousIds);
                    ViewBag.RecommendedAds = recommendedAds; //second viewbag
                    return View("SearchResultsView");
                }
                return View("SearchResultsView");

            }
            return View("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Recommendation()
        {
            var userId = _userManager.GetUserId(this.User);
            if (userId != null)
            {
                var user = await _userManager.FindByIdAsync(userId);

                List<CarAd> recommendedAds = _carAdRepository.ListRecommendedCars(userId, user.PreviousIds);
                return View("SearchResultsView", recommendedAds);
            }

 
            return Index();
        }




        [Authorize]
        [HttpGet]
        public IActionResult UserListings()
        {
            var userId = _userManager.GetUserId(this.User);

PolskaPaliwo/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PolskaPaliwo.Models;

namespace PolskaPaliwo.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> FeedbackSave(int ratingScore)
        {
            var userId = _userManager.GetUserId(this.User);
            if (userId != null)
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    user.LastFeedback = ratingScore;
                    await _userManager.UpdateAsync(user);
                }
                return NoContent();
            }
            return BadRequest();
        }

    }
}

PolskaPaliwo/Views/CarAd/DetailedCarAdvertisementView.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model PolskaPaliwo.Models.CarAd

@{
    ViewData["Title"] = "DetailedCarAdvertisementView";
}

<link rel="stylesheet" href="~/css/EveryAdvertisementDisplaycss.css" />

<h1>Detailed vehicle specification</h1>

<div>
    @if (ViewBag.Source == "fromSearch")
    {
        <a href="@Url.Action("ResultsForPrevious", "CarAd")" class="btn btn-primary ml-2">Back to search results</a>
    }
    else if (ViewBag.Source == "fromHome")
    {
        <a href="@Url.Action("Index", "Home")" class="btn btn-primary ml-2">Back to Home Page</a>
    }
    
    <hr class="custom-hr" />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductionYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mileage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Power)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Power)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EngineSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EngineSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FuelType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Drive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Drive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoorsNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoorsNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OriginCountry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OriginCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstOwner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Features)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Features)
        </dd>*@
    </dl>
    <hr class="custom-hr" />
</div>

<div>
    @if (Model.CreatorId == UserManager.GetUserId(User) && UserManager.GetUserId(User) != null)
    {
        <a href="@Url.Action("DeleteToGenerateForm", "CarAd", new { Id = Model.Id })" class="btn btn-danger">Delete advertisement</a>
    }
    @if (Model.CreatorId == UserManager.GetUserId(User) && UserManager.GetUserId(User) != null)
    {
        <a href="@Url.Action("UpdateToGenerateForm", "CarAd", new { Id = Model.Id })" class="btn btn-primary">Edit advertisement</a>
    }
</div>

PolskaPaliwo/Views/CarAd/SearchResultsView.cshtml
@*@model IEnumerable<PolskaPaliwo.Models.CarAd>*@
@{
    // Retrieve recommended car lists from ViewBag
    var searchresults = ViewBag.SearchResults as List<PolskaPaliwo.Models.CarAd>;
    var recommendedAds = ViewBag.RecommendedAds as List<PolskaPaliwo.Models.CarAd>;
}

@{
    ViewData["Title"] = "SearchResultsView";
}

<link rel="stylesheet" href="~/css/EveryAdvertisementDisplaycss.css" />
<link rel="stylesheet" href="~/css/HideAndShowcss.css" />
<link rel="stylesheet" href="~/css/CollapseAndExpandFeatures.css" />
<link rel="stylesheet" href="~/css/FeedbackForm.css" />

<h1>Search result list</h1>

<p>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back to main page</a>
</p>

@if (searchresults != null && searchresults.Any())
{
    <table class="table table-striped" id="pagination">
        <thead>
            <tr>
                <th>
                    Price
                </th>
                <th>
                    Currency
                </th>
                <th>
                    Condition
                </th>
                <th>
                   Brand
                </th>
                <th>
                   Model
                </th>
                <th>
                   Production year
                </th>
                <th>
                   Mileage
                </th>
                <th>
                   Power
                </th>
                <th>
                   Engine displacement
                </th>
                <th>
                   Fuel type
                </th>
                <th>
                   Drive
                </th>
                <th>
                   Transmission
                </th>
                <th>
                   Type
                </th>
                <th>
                   Number of doors
                </th>
                <th>
                   Colour
                </th>
                <th>
                   Origin country
                </th>
                <th>
                   First owner
                </th>
                <th>
                   Registration year
                </th>
                <th>
                   Location
                </th>
                <th>
                   Telephone
                </th>
                <th>
                   Features
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in searchresults)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Currency)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Condition)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductionYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Mileage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Power)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EngineSize)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FuelType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Drive)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Transmission)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoorsNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Colour)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OriginCountry)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstOwner)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegistrationYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telephone)
                    </td>
                    <td class="features-cell">
                        <div class="features-content hidden">
                            @foreach (var feature in item.Features)
                            {
                                <div>@feature</div>
                            }
                        </div>
                        <button class="expand-btn">Expand</button>
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "Carad", new { id = item.Id, source = "fromSearch" })" class="btn btn-primary">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}



<input type="checkbox" id="toggleRecommendedAds" style="display: none;">
<label for="toggleRecommendedAds">Turn off recommendations</label>

<div id="recommendedAdsSection">
    @if (recommendedAds != null && recommendedAds.Any())
    {
        <div>
            <hr class="custom-hr" />
            <h3>Recommended advertisements</h3>
            <ul class="ad-container">
                @foreach (var carAd in recommendedAds)
                {
                    <a href="@Url.Action("Details", "CarAd", new { id = carAd.Id, source = "fromSearch"})" class="ad-link">
                    <li class="advertisement">
                            @*<img class="ad-image" height="100" width="120" src="@Url.Action("GetImage", "CarAd", new {id = carAd.Id})" />*@
                        <h2 class="ad-heading">@carAd.Brand @carAd.Model</h2>
                        <div class="ad-content">
                            <p>Price: @carAd.Price @carAd.Currency</p>
                            <p>Year: @carAd.ProductionYear</p>
                            <p>Condition: @carAd.Condition</p>
                            <p>Mileage: @carAd.Mileage miles</p>
                        </div>
                    </li>
                    </a>
                }
            </ul>
            <hr class="custom-hr" />
        </div>
    }
</div>






<div>
    <h1 style="text-align: center;">🔵 Feedback scale 🔵</h1>
    <form id="feedbackForm" method="post" asp-controller="User" asp-action="FeedbackSave" class="feedback-form">
        <h3>Please rate your experience:</h3>
        <div class="rating-container">
            <button type="submit" name="ratingScore" value="1" class="rating-button">1</button>
            <button type="submit" name="ratingScore" value="2" class="rating-button">2</button>
            <button type="submit" name="ratingScore" value="3" class="rating-button">3</button>
            <button type="submit" name="ratingScore" value="4" class="rating-button">4</button>
            <button type="submit" name="ratingScore" value="5" class="rating-button">5</button>
            <button type="submit" name="ratingScore" value="6" class="rating-button">6</button>
            <button type="submit" name="ratingScore" value="7" class="rating-button">7</button>
            <button type="submit" name="ratingScore" value="8" class="rating-button">8</button>
            <button type="submit" name="ratingScore" value="9" class="rating-button">9</button>
            <button type="submit" name="ratingScore" value="10" class="rating-button">10</button>
        </div>
    </form>
    <div id="thankYouMessage" style="display: none;">
        <p>Thank you for your feedback!</p>
    </div>
</div>



<script>
document.getElementById("feedbackForm").addEventListener("submit", function (event) {
    // UI changes using JavaScript after form submission
    document.getElementById("feedbackForm").style.display = "none";
    document.getElementById("thankYouMessage").style.display = "block";
});
</script>



<script>
    // Get all expand buttons
    const expandButtons = document.querySelectorAll('.expand-btn');

    // Attach click event listeners to each expand button
    expandButtons.forEach(button => {
        button.addEventListener('click', function () {
            const content = this.previousElementSibling;
            content.classList.toggle('expanded');

            if (content.classList.contains('expanded')) {
                this.innerText = 'Collapse';
            } else {
                this.innerText = 'Expand';
            }
        });
    });
</script>


<script>
    // Retrieve the checkbox and recommended ads section
    const toggleRecommendedAds = document.getElementById('toggleRecommendedAds');
    const recommendedAdsSection = document.getElementById('recommendedAdsSection');

    // Function to toggle the visibility of recommended ads and save state in localStorage
    function toggleAdsVisibility() {
        const toggleLabel = document.querySelector('label[for="toggleRecommendedAds"]');

        if (toggleRecommendedAds.checked) {
            recommendedAdsSection.style.display = 'none';
            localStorage.setItem('adsVisibility', 'hidden');
            toggleLabel.textContent = 'Turn on recommendations'; // Change label text
        } else {
            recommendedAdsSection.style.display = 'block';
            localStorage.setItem('adsVisibility', 'visible');
            toggleLabel.textContent = 'Turn off recommendations'; // Change label text
        }
    }

    // Add event listener to the checkbox
    toggleRecommendedAds.addEventListener('change', toggleAdsVisibility);

    // Check if the visibility state is stored in localStorage
    const savedVisibility = localStorage.getItem('adsVisibility');

    // Set the initial visibility based on the stored state
    if (savedVisibility === 'hidden') {
        toggleRecommendedAds.checked = true;
        recommendedAdsSection.style.display = 'none';

        const toggleLabel = document.querySelector('label[for="toggleRecommendedAds"]');
        toggleLabel.textContent = 'Turn on recommendations'; // Change label text
    }
</script>